### ISSUE TITLE
[Question] output is always empty

### ISSUE THREAD

**Issue by ObaydaAlesawi** [ash-jc-allen/laravel-executor#5] opened 2020-06-26 17:43 UTC
When I was trying to get the output via another place (not command line), it always gives me an empty string `""`
here's the Executor-class code 
```
    public function run(): Executor
    {
        return $this->runArtisan('cache:clear')
            ->runExternal("composer install");
    }
```
uses
(new \App\Executor\AppUpdate())->run()->getOutput()

**Comment by ash-jc-allen** [comment] 2020-06-26 18:30
Hi @Algeneralo, I'm sorry to hear that you're having problems with the package.

I've tried reproducing your error and I can't seem to (it seems to work as expected). What happens if you run the code below?

```php
$executor = (new \App\Executor\AppUpdate())->run()->getOutput();

dd($executor);
```

**Comment by ObaydaAlesawi** [comment] 2020-06-26 18:47
@ash-jc-allen thanks for responding.
it also give me an empty string 
see here's is the output without using `->getOutput()`

```
App\Executor\AppUpdate {#284 ▼
  -output: ""
  -notifier: Joli\JoliNotif\Notifier\ToasterNotifier {#272 ▶}
  +logoPath: "D:\web\test-package\vendor\ashallendesign\laravel-executor\src\Traits/../../resources/img/logo.png"
}
```

**Comment by ObaydaAlesawi** [comment] 2020-06-26 18:50
I think this may help, when commenting the code of Executor Class, line 111 and 112:
```
if (app()->runningInConsole() && ! app()->runningUnitTests()) {
                echo $buffer;
}
```
it give me this message:
`'php' is not recognized as an internal or external command, operable program or batch file. 'composer' is not recognized as an internal or external command, operable program or batch file.`.
I don't know why this message is appear like this, because when I use the command on CL it's working without any issue

**Comment by ash-jc-allen** [comment] 2020-06-26 18:51
@Algeneralo Would you be able to copy and paste the entire class of code where you're trying to run the executor (e.g. - the controller) if possible? Just so that I can get an idea of why it might not be working? :slightly_smiling_face:

**Comment by ObaydaAlesawi** [comment] 2020-06-26 18:55
@ash-jc-allen I'm using it inside the `web.php` file, it's a fresh project so nothing there

**Comment by ash-jc-allen** [comment] 2020-06-26 18:59
I might need to do a little bit of digging on this one. But judging from those error messages, I'd guess that 'php' and 'composer' aren't available for some reason or another.

It could possibly be because it needs to run in a slightly different way when running on Windows. I haven't tested this with Windows (only on Ubuntu and MacOS) so there might be a bug here.

I'll take a look at it later tonight; but if you manage to find a solution, I'd be happy to accept any pull requests for the library :)

**Comment by ObaydaAlesawi** [comment] 2020-06-26 19:01
Yes, I'm using Windows as OS, sure if I found any solution, will share it with you :)

**Comment by ash-jc-allen** [comment] 2020-06-26 22:09
@Algeneralo I'm just doing a little reading up at the moment and have a couple of questions...

- When you typically run your commands on Windows, are you using 'Git Bash' or 'Windows CLI' to run them?
- If you were to open up the Command Prompt (without using Git Bash), navigate to the root of your Laravel app and the run ``` php -v ```, what output do you get?

**Comment by ash-jc-allen** [comment] 2020-06-26 22:31
I have a feeling that your particular error messages are something related to your specific environment setup. But I might be wrong on that. If there is in fact a bug in this library that's causing this issue, I can do some further investigation.

As for the error message not being available through the ``` ->getOutput() ``` method, it looked like there was a bug there. This has been fixed now and should be working as expected. You'll just need to download v1.0.1 for the new fix (release notes: https://github.com/ash-jc-allen/laravel-executor/releases/tag/v1.0.1).

**Closed as completed** 2020-06-29 15:04 UTC

**Comment by ObaydaAlesawi** [comment] 2020-06-29 15:17
@ash-jc-allen sorry for not responding due to work pressure 

- I'm using windows CLI not git Bach
- for `php -v` command, it's working without any issues everywhere 
I will try again with what you fixed and tell you what's happen there
Thanks!
